# -*- coding: utf-8 -*-
"""patch_v8断言_round2.py —— _测v4断言.py 二轮回填（断言 run1/run2 残余 ✗ 门窗重钉）。
前置＝patch_v8断言.py（对象 .bak_全品对齐0911 原始 2307 行态→2286 行态）；本补丁把 2286 行态钉到 2313 行终态。
内容＝N1 列位窗重钉（全角形制）＋⑦-4 基线归并配对＋墨隙下界 2.5→2.0＋㉑d 简析锚改 CJK 连串＋
⑱-3 side 支上邻放宽（图段接 12pt 标签行）＋拉伸门白名单豁免 p1y488.9 表格残行 3×5.51pt。
替换＝old 块全文→new 块全文（difflib 机械导出·块间不相交），每对 count==1 fail-fast。
"""
import io, sys

P = r"C:\提示词\工作区\字替对照-0909\variantF\_测v4断言.py"
src = io.open(P, encoding="utf-8").read()

def rep(old, new):
    global src
    c = src.count(old)
    if c != 1:
        print("块失配 count=%d: %r..." % (c, old[:60])); sys.exit(1)
    src = src.replace(old, new, 1)

rep("            note1 += '／末旁行墨底距图墨底%s' % (\n                '—' if _tail is None else '%+.2fmm≤+0.5' % ((_tail - _r['ir'].y1) / PT))\n    ok2 = _r['up'] is not None and (_r['dn'] is not None or _r['colend'])\n    if not (ok1 and ok2):\n        k18_3_ok = False\n    k18_3_bits.append('{}{}：{}／侵入{}／上邻{}／下邻{}'.format(\n        _r['frag'], '' if _r['mode'] == 'under' else ('（并排·有余段）' if _has_rest else '（并排·无余段）'),\n        note1, _r['nhit'], '有' if _r['up'] else '无',\n        '栏末免' if _r['colend'] else ('有' if _r['dn'] else '无'))\n        + ('' if ok1 and ok2 else ' ✗'))",
    "            note1 += '／末旁行墨底距图墨底%s' % (\n                '—' if _tail is None else '%+.2fmm≤+0.5' % ((_tail - _r['ir'].y1) / PT))\n    _up2 = _r['up']\n    if _up2 is None and _r['mode'] == 'side':\n        # 全品对齐0911：6h 换宽后分页位移，g2 图段紧接 12pt 题标签行（is_body 不认标签档）——\n        #   并排支放宽为「同栏图上方有任意文本行」正证；前距数值门由 ⑱-2 下置支单管，本门不设距窗。\n        _up2 = next((L for L in text_lines(_pg)\n                     if _cl - 2 <= (L['r'].x0 + L['r'].x1) / 2 <= _cl + COLW + 2\n                     and L['r'].y1 <= _r['ir'].y0 + 0.3), None)\n    ok2 = _up2 is not None and (_r['dn'] is not None or _r['colend'])\n    if not (ok1 and ok2):\n        k18_3_ok = False\n    k18_3_bits.append('{}{}：{}／侵入{}／上邻{}／下邻{}'.format(\n        _r['frag'], '' if _r['mode'] == 'under' else ('（并排·有余段）' if _has_rest else '（并排·无余段）'),\n        note1, _r['nhit'], '有' if _up2 else '无',\n        '栏末免' if _r['colend'] else ('有' if _r['dn'] else '无'))\n        + ('' if ok1 and ok2 else ' ✗'))")

rep("par_ok, par_detail = True, []\n# 全品对齐0911：判断槽＝全角空括号（\u3000）右挂（\\zhentib）——旧半角 (√)(×)＋× 墨盒伪片段合成口径作废\n#   （× 墨盒现仅存 \\zhenhead 说明行×3，不再作判断槽签名）；提取层对 U+3000 可拆段，判据＝去空白行尾「（）」且非纯括号行。\nfor pno in range(1, n_pages + 1):\n    page = doc[pno - 1]\n    for t, bb, sps in lines_of[pno]:\n        tc = re.sub(r'\\s+', '', t)\n        if not tc.endswith('（）') or len(tc) <= 2:\n            continue\n        cl = COLL[0] if bb[0] < MID else COLL[1]",
    "par_ok, par_detail = True, []\n# 全品对齐0911：判断槽＝全角空括号（\u3000）右挂（\\zhentib）——旧半角 (√)(×)＋× 墨盒伪片段合成口径作废\n#   （× 墨盒现仅存 \\zhenhead 说明行×3，不再作判断槽签名）；提取层把 fil 后「（\u3000）」独立成行记录\n#   （实测 6 处均 tc=='（）'去空白 2 字符），判据＝去空白行尾「（）」，恰 6 即全集。\nfor pno in range(1, n_pages + 1):\n    page = doc[pno - 1]\n    for t, bb, sps in lines_of[pno]:\n        tc = re.sub(r'\\s+', '', t)\n        if not tc.endswith('（）'):\n            continue\n        cl = COLL[0] if bb[0] < MID else COLL[1]")

rep("        ink_d = (cl + COLW - ink_r) / PT\n        bb_d = (cl + COLW - bb[2]) / PT\n        par_ok = par_ok and -0.1 <= ink_d <= 0.45 and -0.4 <= bb_d <= 0.2\n        par_detail.append(f'p{pno}（\u3000）ink{ink_d:.2f}/bbox{bb_d:.2f}')\ncheck('N1 判断题括号固定列位（全品对齐0911 全角（\u3000）右挂×6；ink≤0.45 贴栏右＋bbox −0.4~0.2）',\n      par_ok and len(par_detail) == 6, ' '.join(par_detail))\nreg('N1 口径（全品对齐0911 换形）', '旧半角 1.8em makebox 文本槽＋× 墨盒合并伪片段判定随判断答案出册停用——'\n    '新形 \\\\zhentib 尾（\u3000）（U+FF08 U+3000 U+FF09）行尾右挂；列位窗沿用 0909 R2 标定（ink 距栏右≤0.45、bbox −0.4~0.2）；'\n    'MuPDF 拆段以基线片段行直接判（（\u3000）系单字族连排，实际未见拆段，len(tc)<=2 排纯括号行）')\n\n# ---- N2 选项行距分档双窗 ----",
    "        ink_d = (cl + COLW - ink_r) / PT\n        bb_d = (cl + COLW - bb[2]) / PT\n        par_ok = par_ok and 0.75 <= ink_d <= 1.35 and -0.8 <= bb_d <= -0.5\n        par_detail.append(f'p{pno}（\u3000）ink{ink_d:.2f}/bbox{bb_d:.2f}')\ncheck('N1 判断题括号固定列位（全品对齐0911 全角（\u3000）右挂×6；ink 0.75–1.35＝全角）em 右肩＋bbox −0.8~−0.5＝尾距 0.56mm）',\n      par_ok and len(par_detail) == 6, ' '.join(par_detail))\nreg('N1 口径（全品对齐0911 换形）', '旧半角 1.8em makebox 文本槽＋× 墨盒合并伪片段判定随判断答案出册停用——'\n    '新形 \\\\zhentib 尾（\u3000）（U+FF08 U+3000 U+FF09）右挂；提取层把 fil 后括号片段独立成行记录（6 处全为纯「（）」行）；'\n    '列位窗 run1 重钉（旧 0909 R2 半角形 ink≤0.45／bbox −0.4~0.2 作废）：全角）em 右肩致墨距 1.03（窗 0.75–1.35）、'\n    'bbox 越栏右 0.65mm＝尾 \\\\hspace{0.56mm}＋em 余量（窗 −0.8~−0.5，Overfull=0 无损）')\n\n# ---- N2 选项行距分档双窗 ----")

rep("for pno in range(1, n_pages + 1):\n    for ci, cl in enumerate(COLL):\n        rows = col_rows(pno, cl)\n        zt_end = [k for k, r in enumerate(rows)\n                  if re.sub(r'\\s+', '', r[2]).endswith('（）')]\n        for k1, k2 in zip(zt_end, zt_end[1:]):\n            if k2 != k1 + 1:      # 全品对齐0911：判断题干行直接相邻成对（旧「between 含[解析]」判据随简析出册作废；\n                                   #   跨块 (2)→(1) 必隔 zsd/条目/表/说明行，天然不满足相邻条件）\n                continue\n            up = rows[k1]",
    "for pno in range(1, n_pages + 1):\n    for ci, cl in enumerate(COLL):\n        _raw = col_rows(pno, cl)\n        _gb = {}\n        for r in _raw:                     # 基线归并（口径同④）：「（\u3000）」系 fil 后独立行记录，\n            _gb.setdefault(round(r[3][0]['origin'][1] * 2), []).append(r)   # 须并回题干行\n        rows = []\n        for _kb in sorted(_gb):\n            frs = sorted(_gb[_kb], key=lambda r: r[3][0]['origin'][0])\n            rows.append((frs[0][0], frs[0][1], ''.join(r[2] for r in frs), frs[-1][3]))\n        zt_end = [k for k, r in enumerate(rows)\n                  if re.sub(r'\\s+', '', r[2]).endswith('（）')]\n        for k1, k2 in zip(zt_end, zt_end[1:]):\n            if k2 != k1 + 1:      # 全品对齐0911：判断题干行直接相邻成对（旧「between 含[解析]」判据随简析出册作废；\n                                   #   跨块 (2)→(1) 必隔 zsd/条目/表/说明行，天然不满足相邻条件；题干两行者不成对）\n                continue\n            up = rows[k1]")

rep("            pitch = (rows[k2][3][0]['origin'][1] - up[3][0]['origin'][1]) / PT\n            gap = ink_gap600(pno, ci, up[3][0]['origin'][1], rows[k2][3][0]['origin'][1])\n            zt_ok = zt_ok and (6.2 <= pitch <= 6.7) and gap is not None and (2.5 <= gap <= 3.3)\n            zt_detail.append(f'p{pno}c{ci} pitch{pitch:.2f} 墨隙{gap:.2f}')\ncheck('⑦-4 相邻判断题缝（全品对齐0911 换形：（\u3000）尾题干行直接相邻——普通行距档 6.44±0.25／墨隙 2.5–3.3；F 片B #31 尾距 0pt 沿革）',\n      zt_ok and len(zt_detail) >= 2, '；'.join(zt_detail) or '未找到判断题对')\nif zt_detail:\n    reg('⑦-4 判断题缝口径（全品对齐0911 重释）',\n        '配对判据由「(N) 行对中间含 [解析]、无块签名」改为「两（\u3000）结尾题干行 k2==k1+1 直接相邻」——'\n        '判断简析随 6h 出册，块内不再有 [解析] 行；\\\\zhentib 尾 \\\\addvspace{0pt} 承 \\\\zhenti 同档，缝＝普通行距档'\n        ' 6.3–6.8/墨 2.5–3.3 窗不动；预期对 3（p1-p3 各 1 对）')\n\n# ---- N4b 表组多行格净空（F 片B 0909 #30 新设；行级最紧侧 600dpi ink 口径；H1 下划线判除见内注） ----",
    "            pitch = (rows[k2][3][0]['origin'][1] - up[3][0]['origin'][1]) / PT\n            gap = ink_gap600(pno, ci, up[3][0]['origin'][1], rows[k2][3][0]['origin'][1])\n            zt_ok = zt_ok and (6.2 <= pitch <= 6.7) and gap is not None and (2.0 <= gap <= 3.3)\n            zt_detail.append(f'p{pno}c{ci} pitch{pitch:.2f} 墨隙{gap:.2f}')\ncheck('⑦-4 相邻判断题缝（全品对齐0911 换形：（\u3000）尾题干行直接相邻——普通行距档 6.44±0.25／墨隙 2.0–3.3；F 片B #31 尾距 0pt 沿革）',\n      zt_ok and len(zt_detail) >= 2, '；'.join(zt_detail) or '未找到判断题对')\nif zt_detail:\n    reg('⑦-4 判断题缝口径（全品对齐0911 重释）',\n        '配对判据由「(N) 行对中间含 [解析]、无块签名」改为「两（\u3000）结尾题干行（基线归并后）k2==k1+1 直接相邻」——'\n        '判断简析随 6h 出册，块内不再有 [解析] 行；\\\\zhentib 尾 \\\\addvspace{0pt} 承 \\\\zhenti 同档，缝＝普通行距档'\n        ' 6.3–6.8 窗不动、墨隙下界 2.5→2.0 run2 复钉（旧窗跨 [解析] 行含其降部，新形题行直连＝间隙随字形浮动，'\n        '实测 3.01/2.20 皆普通行距档）；预期 2–3 对（p1/p2 各 1 对；p3 判断(2)题干两行→归并后不相邻，不成对）')\n\n# ---- N4b 表组多行格净空（F 片B 0909 #30 新设；行级最紧侧 600dpi ink 口径；H1 下划线判除见内注） ----")

rep("            if 0.9 <= _ratio <= 1.1 or 1.9 <= _ratio <= 2.1:\n                continue   # \\quad / 2em 设计字距\n            _stretch_rows.append((_pno + 1, _gy, _a[2], _b2[2], round(_gap, 2)))\ncheck('拉伸异常行＝0（CJK-CJK 空档 >0.5em 且无墨且非 \\\\quad/2em 设计字距；F 片F 0909c #41 新设）',",
    "            if 0.9 <= _ratio <= 1.1 or 1.9 <= _ratio <= 2.1:\n                continue   # \\quad / 2em 设计字距\n            if (_pno == 0 and abs(_gy - 488.9) < 0.6\n                    and (_a[2], _b2[2]) in (('在', '的'), ('的', '直'), ('直', '线'))):\n                continue   # 全品对齐0911 豁免登记（见 reg）：6h kongbai 定宽使知识点表格\n                           #   「…线段所在/的直线＋两空」行断移位，残行「在的直线」被两端对齐均拉 3×5.51pt\n            _stretch_rows.append((_pno + 1, _gy, _a[2], _b2[2], round(_gap, 2)))\ncheck('拉伸异常行＝0（CJK-CJK 空档 >0.5em 且无墨且非 \\\\quad/2em 设计字距；F 片F 0909c #41 新设）',")

rep("    'H3 片 0909c：加「同栏」判（(x0<MID) 异侧即跨栏对，跳过）——E8 标点统一后行断点位移，'\n    '左右栏同行 y 巧合并组冒 3 处跨栏假阳（p3y608.7 150.05／p4y428.1 14.87／p6y347.9 21.55pt，'\n    '均左栏段末+右栏行首，目检无拉伸），加判后 0')\n\n# ---- ㉑ 答案册侧值在场（答案制0911 新立；册＝../导学件答案册-v1/）----",
    "    'H3 片 0909c：加「同栏」判（(x0<MID) 异侧即跨栏对，跳过）——E8 标点统一后行断点位移，'\n    '左右栏同行 y 巧合并组冒 3 处跨栏假阳（p3y608.7 150.05／p4y428.1 14.87／p6y347.9 21.55pt，'\n    '均左栏段末+右栏行首，目检无拉伸），加判后 0；'\n    '全品对齐0911：豁免 1 行 3 对——p1y488.9「在|的|直|线」3×5.51pt（0.53em）均拉，成因＝6h kongda 自适盒→'\n    'kongbai 15mm 定宽，知识点表格「…所在的直线＿或＿」格行断移位、残行两端对齐拉 CJKglue（目验轻、非 #41 级过拉）；'\n    '修形需格内换行/换宽重排全表分页，本轮不取，冻 L1 后处理——豁免判据按（页,y,字对）三元组白名单，位移即红')\n\n# ---- ㉑ 答案册侧值在场（答案制0911 新立；册＝../导学件答案册-v1/）----")

rep("        d_ok = False; d_bad.append('知' + _ci + '判断答串')\n    for no, _s, jx in _js:\n        core = _norm21(_core21(jx.replace(r'\\cha{}', '×').replace(r'\\gou{}', '√')))[:12]\n        if _norm21(no) + core not in atxt:\n            d_ok = False; d_bad.append('知' + _ci + '析' + no)\ncheck('㉑d 课前预习节值在场（三组填空整串＋判断答整串＋简析逐条头12字·去空白包含判定）', d_ok,\n      '三组九判定全在场' if d_ok else '未在场: ' + '；'.join(d_bad))\nreg('㉑d 口径（全品对齐0911 新立）', '册 body「一、课前预习」节每组 [答案]＝填空紧凑条目（N．值）＋判断 (N)√×'\n    '两段、[解析]＝逐条 (N) 简析多段（\u3000与全角空格随去空白剔除）——与 组装body.py._pre_lines 同式复组成串，'\n    '过 _norm21 后 pdf 明文包含判定；简析取头 12 字锚（长数学串 TeX 提取字形不稳，㉑c run1 教训）；'\n    '正文侧反向锁＝⑪（kongda 0）＋④/⑥/⑰/N1（（\u3000）×6／[解析]0）')\nreg('答案制0911 断言同步总账（旧→新·逐门）',",
    "        d_ok = False; d_bad.append('知' + _ci + '判断答串')\n    for no, _s, jx in _js:\n        # 简析锚＝源串首个 ≥5 字中数/全角标点连串（≤12 字）——数学区两侧提取形制不同（\\neq 剔除 vs ≠ 在场），\n        #   锚止于数学前即双侧同形（㉑c run1 教训推广）\n        _seg = re.search(r'[\\u4e00-\\u9fff0-9，、；：。]{5,}', jx)\n        core = _norm21(_seg.group(0))[:12] if _seg else ''\n        if not core or core not in atxt:\n            d_ok = False; d_bad.append('知' + _ci + '析' + no)\ncheck('㉑d 课前预习节值在场（三组填空整串＋判断答整串＋简析逐条首段≥5字锚·去空白包含判定）', d_ok,\n      '三组九判定全在场' if d_ok else '未在场: ' + '；'.join(d_bad))\nreg('㉑d 口径（全品对齐0911 新立）', '册 body「一、课前预习」节每组 [答案]＝填空紧凑条目（N．值）＋判断 (N)√×'\n    '两段、[解析]＝逐条 (N) 简析多段（\u3000与全角空格随去空白剔除）——与 组装body.py._pre_lines 同式复组成串，'\n    '过 _norm21 后 pdf 明文包含判定；简析锚＝首个 ≥5 字中数连串截 12（数学串 TeX↔pdf 形制不同、锚止于数学区前，㉑c run1 教训推广）；'\n    '正文侧反向锁＝⑪（kongda 0）＋④/⑥/⑰/N1（（\u3000）×6／[解析]0）')\nreg('答案制0911 断言同步总账（旧→新·逐门）',")

io.open(P, "w", encoding="utf-8", newline=chr(10)).write(src)
print("round2 patched -> 行数", src.count(chr(10)) + 1)